version: '3.8'

services:
#  metrics-app:
#    build: ./
#    command: ./metrics-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    restart: always
    image: postgres:14.6-alpine
    container_name: db_metrics
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
#    volumes:
#      - ./.database/postgres/data:var/lib/postgresql/data
    ports:
      - "5432:5432"